config/routes.rb
Rails.application.routes.draw do
  resources :followings, only: [:new, :create, :destroy]
  resources :opinions, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :edit, :show, :new, :create, :update, :destroy]

  root "opinions#index"

  resources :sessions, only: [:new, :create, :destroy]

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  get "vote", to: "opinions#update_vote", as: "vote"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: 'User', foreign_key: :followerId
  belongs_to :followed, class_name: 'User', foreign_key: :followedId
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :set_following, only: %i[show edit update destroy]

  # GET /followings
  # GET /followings.json
  def index
    login_required
    @followings = Following.all
  end

  # GET /followings/1
  # GET /followings/1.json
  def show; end

  # GET /followings/new
  def new
    @following = Following.new
  end

  # POST /followings
  # POST /followings.json
  def create
    @following = Following.new(following_params)
    respond_to do |format|
      if @following.save
        format.html { redirect_to opinions_path, notice: 'Following was successfully created.' }
        format.json { render :show, status: :created, location: @following }
      else
        format.html { render :new }
        format.json { render json: @following.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /followings/1
  # PATCH/PUT /followings/1.json
  def update
    respond_to do |format|
      if @following.update(following_params)
        format.html { redirect_to @following, notice: 'Following was successfully updated.' }
        format.json { render :show, status: :ok, location: @following }
      else
        format.html { render :edit }
        format.json { render json: @following.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followings/1
  # DELETE /followings/1.json
  def destroy
    respond_to do |format|
      if @following.destroy_all
        format.html { redirect_to opinions_path, notice: 'Following was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :destroy }
        format.json { render json: @following.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_following
    @following = Following.where(followerId: current_user.id, followedId: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def following_params
    params.require(:following).permit(:followerId, :followedId)
  end
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/views/followings/_form.html.erb
<%= form_with(model: following, local: true) do |form| %>
  <%= display_errors(following) %>

  <div class="field">
    <%= form.label :followerId %>
    <%= form.number_field :followerId %>
  </div>

  <div class="field">
    <%= form.label :followedId %>
    <%= form.number_field :followedId %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/followings/edit.html.erb
<h1>Editing Following</h1>

<%= render 'form', following: @following %>

<%= link_to 'Show', @following %> |
<%= link_to 'Back', followings_path %>

app/views/followings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Followings</h1>

<table>
  <thead>
    <tr>
      <th>Followerid</th>
      <th>Followedid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @followings.each do |following| %>
      <tr>
        <td><%= following.followerId %></td>
        <td><%= following.followedId %></td>
        <td><%= link_to 'Show', following %></td>
        <td><%= link_to 'Edit', edit_following_path(following) %></td>
        <td><%= link_to 'Destroy', following, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Following', new_following_path %>

app/views/followings/new.html.erb
<h1>New Following</h1>

<%= render 'form', following: @following %>

<%= link_to 'Back', followings_path %>

app/views/followings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Followerid:</strong>
  <%= @following.followerId %>
</p>

<p>
  <strong>Followedid:</strong>
  <%= @following.followedId %>
</p>

<%= link_to 'Edit', edit_following_path(@following) %> |
<%= link_to 'Back', followings_path %>