config/routes.rb
Rails.application.routes.draw do
  resources :followings, only: [:new, :create, :destroy]
  resources :opinions, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :edit, :show, :new, :create, :update, :destroy]

  root "opinions#index"

  resources :sessions, only: [:new, :create, :destroy]

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  get "vote", to: "opinions#update_vote", as: "vote"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_left_sidebar.html.erb
<div class="d-flex align-items-center p-3">
  <%= image_tag current_user.photo.url(:thumb) %>
  <h3 class="mx-3 text-muted"><%= current_user.fullname %></h3>
</div>

<div class="d-flex my-3 justify-content-center align-items-center ">
  <div class="d-flex flex-column justify-content-center align-items-center pl-1 pr-4 ">
    <h1 ><%= link_to current_user.followeds.size, users_path(id: current_user.id, flag: "followed_users"), :class => "text-white"%> </h1>
    <p class="text-muted">followed</p>
  </div>
  <div class="d-flex flex-column justify-content-center align-items-center pl-4 pr-1 ">
    <h1 ><%= link_to current_user.followers.size, users_path(id: current_user.id, flag: "followers"), :class => "text-white"%> </h1>
    <p class="text-muted">followers</p>
  </div>
</div>

<div class="d-flex flex-column align-items-center left_sidebar_links">
  <h2 class="my-2"><%= link_to '<i class="fa fa-user mr-3 text-muted"></i> Profile'.html_safe, user_path(current_user) %></h2>
  <h2 class="my-2"><%= link_to '<i class="fa fa-home mr-3 text-muted"></i> Home'.html_safe, opinions_path %></h2>
  <h2 class="mt-5"><%= link_to '<i class="fas fa-sign-out-alt mr-3 text-muted"></i> Logout'.html_safe, logout_url %></h2>
</div>

app/views/layouts/_top_navbar.html.erb
<div class="mr-auto align-self-center">
  <i class="fab fa-twitter fa-2x ml-4"></i>
</div>
<div class="align-self-center text-muted">
  <i class="fas fa-pen fa-2x mr-5"></i>
  <i class="fas fa-envelope fa-2x mr-5"></i>
  <i class="fas fa-search fa-2x mr-5"></i>
  <i class="fas fa-cog fa-2x mr-5"></i>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTwitterRedesign</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
     <% if current_user %>
     <div class="d-flex text-light all-info">
       <div class="flex-shrink-1 left_sidebar w-25">
         <%= render 'layouts/left_sidebar' %>
       </div>
       <div class="w-100 d-flex flex-column ">
         <div class="top_navbar d-flex flex-nowrap">
          <%= render 'layouts/top_navbar' %>
         </div>
         <div class="bg-light">
           <%= yield %>
         </div>
       </div>
     </div>
     <% else %>
     <div class="bg-light">
       <%= yield %>
     </div>
     <% end %>
  </body>
</html>